Added trap to kill spinner on interrupt
alces-software/clusterware pull request #238
Opened 2017-05-16 11:46 UTC by WilliamMcCumstie

Added a trap to `ui.functions.sh` `toggle_spin` method to prevent the spinner from continuing after the calling script has terminated on interrupt. 

This fixes #219  where interrupting the synchronous script means the spinner continuous.

2017-05-16 11:51 UTC, mjtko commented on lib/functions/ui.functions.sh
> +  exit 1
Why the `exit 1`?

2017-05-16 12:05 UTC, mjtko commented
We should be aware that there can only be one trap function per signal... http://stackoverflow.com/a/7287873/928027 is quite informative.

It might be best to deal with this by adding a library function (or several) for handling trap management (may be best suited within the `process` library)?

e.g.

`process_trap_add <fn name> <signal>`
`process_trap_remove <fn name> <signal>`

Maybe could do things like this (off the top of my head):

```
process_trap_handle() {
  local signal trap_list_var
  signal=$1
  trap_list_var="_PROCESS_${signal}"
  for fn in ${!trap_list_var}; do
    $fn
  done
}

process_trap_add() {
  local fn signal trap_list_var
  fn="$1"
  signal="$2"

  trap_list_var="_PROCESS_${signal}"
  declare $trap_list_var="${!trap_list_var} $fn"
  trap "process_trap_handle $signal" $signal
}
```

2017-05-16 14:45 UTC, WilliamMcCumstie commented
Probably a good idea. Currently working on `process_trap_handler` on a separate branch. Then will merge in with this PR

2017-05-17 13:57 UTC, WilliamMcCumstie commented
I have created the `trap handler` which allows multiple traps to be added for the same signal. It operates similarly to what mark as described above. In short a `process_trap_handler` is invoked when the signal is sent. The handler then executes a string of commands that can be added to with `process_trap_add`.

As their can only be one `exit` as part of the trap, I prevent `process_trap_add <SIGNAL> exit` from exiting the script. Instead use `process_trap_set_exit` to set the exit which insures all the traps run before exiting. By default the trap does not exit.

The `spinner` will causes  the process to `exit` iff no exit status as been set for the trap. If the exit status as already been set, it does not modify it.

2017-05-17 14:58 UTC, mjtko requested changes

2017-05-17 14:58 UTC, mjtko commented on lib/functions/ui.functions.sh
> +            if [ ! $(process_trap_get_exit INT) ]; then
This can be simplified to:

```
if ! process_trap_get_exit INT >/dev/null; then
```

This also avoids creating an additional subshell.

2017-05-17 14:58 UTC, mjtko commented on CHANGELOG.md
> +- Added a `trap` handler to `process.function.sh`
"Signal trap handling added to the `process` function library"

2017-05-17 14:58 UTC, mjtko commented on CHANGELOG.md
> +- Prevents the `ui-spinner` from continuing on process interrupt
"The progress spinner no longer continues spinning forever when the process receives an interrupt signal"

2017-05-17 14:58 UTC, mjtko commented on lib/functions/ui.functions.sh
> +_ui_trap_sig() {
I'm not sure this is a descriptive name. Maybe `_ui_spinner_killer`?

2017-05-17 14:58 UTC, mjtko commented on lib/functions/ui.functions.sh
> +            process_trap_add INT '_ui_trap_sig'
Just a note: no need for the quotes here (it'll be interpreted as a string parameter regardless).

2017-05-17 14:58 UTC, mjtko commented on lib/functions/process.functions.sh
> +  echo $(eval ${!trap_list_var})
I'm not keen on using `echo` and `eval` here.  Is there a reason why this can't be used:

```
${!trap_list_var}
```

2017-05-17 18:16 UTC, mjtko requested changes

2017-05-17 18:16 UTC, mjtko commented on lib/functions/process.functions.sh
> +  shift 2
This `shift` is superfluous.

2017-05-17 18:16 UTC, mjtko commented on lib/functions/ui.functions.sh
> +            if ! process_trap_get_exit INT >/dev/null; then
After looking at this a little longer, it feels a bit unwieldy.

Maybe we could change `process_trap_set_exit` s.t. it only sets the exit code supplied if one isn't already set?

Perhaps:

```
process_trap_exit_on INT
```
...With a default of exit code `1` if it's not supplied?

2017-05-22 14:11 UTC, mjtko approved these changes

2017-05-22 14:11 UTC, mjtko commented
:+1:

2017-05-22 14:11 UTC, merged